# frozen_string_literal: true

# generated by chatgpt with prompt
# can you generate some tests using cucumber for BDD using this user model?
# **user model code**
# heavily edited down because testing oauth is really hard

Given('I am on the login page') do
  visit root_path
end

Then('I should see {string}') do |text|
  expect(page).to have_content(text)
end
