# generated by chatgpt with prompt
# can you generate some tests using cucumber for BDD using this user model?
# **user model code**

Given('I am on the homepage') do
  visit root_path
end

When('I click {string}') do |link|
  click_link link
end

When('I authenticate successfully with Google') do
  mock_google_auth('john.doe@example.com', 'John Doe', 'http://example.com/image.jpg')
  click_link 'Sign in with Google'
end

When('I authenticate successfully with Google as {string}') do |email|
  mock_google_auth(email, 'Existing User', 'http://example.com/image.jpg')
  click_link 'Sign in with Google'
end

Then('I should see {string}') do |text|
  expect(page).to have_content(text)
end

Then('a user record should exist with email {string}') do |email|
  user = User.find_by(email: email)
  expect(user).not_to be_nil
  expect(user.email).to eq(email)
end

Then('there should still be only one user record with email {string}') do |email|
  expect(User.where(email: email).count).to eq(1)
end

Given('a user with email {string} and provider {string} exists') do |email, provider|
  User.create!(
    email: email,
    provider: provider,
    uid: 'existing_uid',
    name: 'Existing User',
    image: 'http://example.com/old_image.jpg'
  )
end

def mock_google_auth(email, name, image)
  OmniAuth.config.test_mode = true
  OmniAuth.config.mock_auth[:google_oauth2] = OmniAuth::AuthHash.new(
    {
      provider: 'google_oauth2',
      uid: '123456789',
      info: {
        name: name,
        email: email,
        image: image
      }
    }
  )
end
