name: CodeClimate and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_analyze:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cybercrm_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.2'

    - name: Configure Bundler
      run: |
        mkdir -p .bundle
        echo 'BUNDLE_PATH: ".bundle"' > .bundle/config
        echo 'BUNDLE_DISABLE_SHARED_GEMS: "true"' >> .bundle/config
        echo 'BUNDLE_DEPLOYMENT: "true"' >> .bundle/config
        echo 'BUNDLE_WITHOUT: "development:test"' >> .bundle/config

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
      working-directory: ./cybercrm

    - name: Set up database configuration
      run: cp config/database.yml.ci config/database.yml
      working-directory: ./cybercrm

    - name: Create and migrate the database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
      env:
        RAILS_ENV: test
      working-directory: ./cybercrm

    - name: Run tests
      run: bundle exec rspec
      env:
        RAILS_ENV: test
      working-directory: ./cybercrm

    - name: CodeClimate Coverage Action
      uses: paambaati/codeclimate-action@v8.0.0
      with:
        coverageCommand: bundle exec rspec
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        RAILS_ENV: test
