name: CodeClimate and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_analyze:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cybercrm_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.2' # specify your ruby version

    - name: Install dependencies
      run: |
        cd ./cybercrm
        bundle install

    - name: Set up database configuration
      run: |
        cp ./cybercrm/config/database.yml.ci ./cybercrm/config/database.yml

    - name: Create and migrate the database
      run: |
        cd ./cybercrm
        bundle exec rails db:create
        bundle exec rails db:schema:load
      env:
        RAILS_ENV: test

    - name: Run tests
      run: |
        cd ./cybercrm
        bundle exec rspec
      env:
        RAILS_ENV: test

    - name: Upload coverage to Code Climate
      uses: paambaati/codeclimate-action@v8.0.0
      with:
        coverageCommand: cd ./cybercrm && bundle exec rspec
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        RAILS_ENV: test
